name: Deploy to EC2

on:
  push:
    branches:
      - main  # Se activará en cada push a la rama 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adoptopenjdk'  # Agrega la distribución

      - name: Build with Maven
        run: mvn clean install -DskipTests

      - name: Deploy to EC2
        run: |
          # Aquí puedes agregar tus comandos para desplegar el .war en EC2
          # Como ejemplo:
          scp -i ${{ secrets.EC2_PRIVATE_KEY }} target/webapp-1.0-SNAPSHOT.war ubuntu@23.22.192.42:/opt/tomcat/webapps/
          ssh -i ${{ secrets.EC2_PRIVATE_KEY }} ubuntu@23.22.192.42 'sudo systemctl restart tomcat'
        env:
          EC2_IP: ${{ secrets.EC2_IP }}
